name: Patum
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  just_audio: ^0.9.46
  flutter_phone_direct_caller: ^2.1.1
  camerawesome: ^2.1.0
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  loader_overlay: ^5.0.0
  flutter_spinkit: ^5.2.1
  google_generative_ai: ^0.4.0
  image_picker: ^1.0.7
  flutter_tts: ^3.8.5
  record: ^5.0.4
  permission_handler: ^11.3.0
  uuid: ^4.3.3
  flutter_dotenv: ^5.0.2
  provider: ^6.0.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  curved_navigation_bar: ^1.0.6
  animated_text_kit: ^4.2.3
  firebase_storage: ^12.4.5
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Patum.png"
  adaptive_icon_foreground: "assets/Patum.png"
  adaptive_icon_background: "#ffffff"  # or use an image here too


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/AlertSound.mp3
    - .env

  fonts:
    - family: Source3
      fonts:
        - asset: fonts/SourceSans3-VariableFont_wght.ttf

    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: SourcePro
      fonts:
        - asset: fonts/SourceCodePro-VariableFont_wght.ttf

    - family: Montessart_Mid
      fonts:
        - asset: fonts/Montserrat-Medium.ttf

    - family: Sacramento
      fonts:
        - asset: fonts/Sacramento-Regular.ttf
